title: Homelab Docs
description: This is the documentation of my homelab setup and configuration. Multiple containers are running on k3s.
theme: just-the-docs

url: https://docs.yannikmueller.eu

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
